# Generated by Django 4.0.6 on 2022-08-06 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='church_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=30)),
                ('request', models.TextField(max_length=200)),
                ('type_choices', models.CharField(choices=[('solo', 'Unique'), ('trio', 'Tridium'), ('nine', 'Neuvaine'), ('month', 'Trentaine')], max_length=30)),
                ('hours', models.CharField(max_length=255)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField()),
            ],
        ),
    ]
