# Generated by Django 4.1.3 on 2023-02-06 17:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom ')),
                ('status', models.CharField(choices=[('top', 'Paroisse'), ('second', 'Station secondaire')], max_length=30, verbose_name='Status')),
                ('archdiocese', models.CharField(max_length=30, verbose_name='Archidiocèse ')),
                ('priest', models.CharField(max_length=100, verbose_name='Curé ')),
                ('mother_parish', models.CharField(blank=True, max_length=100, null=True, verbose_name='Paroisse mère ')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='Contenu ')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request.Suggestion.church+', to='request.church')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Church_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=30, verbose_name='Demandée par ')),
                ('request', models.TextField(max_length=200, verbose_name='Intention (Veuillez être clair, précis et bref)\n')),
                ('type_choices', models.CharField(choices=[('solo', 'Unique'), ('trio', 'Tridium'), ('nine', 'Neuvaine'), ('month', 'Trentaine')], max_length=30, verbose_name='Type de messe ')),
                ('hours', models.CharField(max_length=255, verbose_name='Horaires ')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Date de début ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin ')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church', to='request.church')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Contenu ')),
                ('content', models.CharField(max_length=200, verbose_name='Contenu ')),
                ('illustration', models.ImageField(blank=True, default=None, null=True, upload_to='images/illustrations/%Y/%m/%d/')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_announcement', to='request.church')),
            ],
        ),
    ]
