# Generated by Django 4.0.6 on 2022-08-09 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church_request',
            name='customer',
            field=models.CharField(max_length=30, verbose_name='Demandée par '),
        ),
        migrations.AlterField(
            model_name='church_request',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin '),
        ),
        migrations.AlterField(
            model_name='church_request',
            name='hours',
            field=models.CharField(max_length=255, verbose_name='Horaires '),
        ),
        migrations.AlterField(
            model_name='church_request',
            name='request',
            field=models.TextField(max_length=200, verbose_name='Intention (Veuillez être clair, précis et bref)\n'),
        ),
        migrations.AlterField(
            model_name='church_request',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date de début '),
        ),
        migrations.AlterField(
            model_name='church_request',
            name='type_choices',
            field=models.CharField(choices=[('solo', 'Unique'), ('trio', 'Tridium'), ('nine', 'Neuvaine'), ('month', 'Trentaine')], max_length=30, verbose_name='Type de messe '),
        ),
    ]
