# Generated by Django 4.1.3 on 2023-01-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_church_request_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom ')),
                ('status', models.CharField(choices=[('top', 'Paroisse'), ('second', 'Station secondaire')], max_length=30, verbose_name='Status')),
                ('archdiocese', models.CharField(max_length=30, verbose_name='Archidiocèse ')),
                ('priest', models.CharField(max_length=100, verbose_name='Curé ')),
                ('mother_parish', models.CharField(blank=True, max_length=100, null=True, verbose_name='Curé ')),
            ],
        ),
    ]
