# Generated by Django 4.1.3 on 2023-02-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_announcement_church_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='church',
            new_name='announcement_church',
        ),
        migrations.RenameField(
            model_name='church_request',
            old_name='church',
            new_name='request_church',
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='church',
            new_name='suggestion_church',
        ),
    ]
